# Generated by Django 5.2 on 2025-05-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_blog_options_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
